name: MSBuild

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    env:
      KB_DRIVER_RELEASE_ZIP_URL: https://github.com/HoShiMin/Kernel-Bridge/releases/latest/download/Kernel-Bridge.zip
      KB_TARGET_ZIP: KB.zip
      KB_EXTRACT_DRIVER_PATH: KB/x64/Release
    steps:
      - uses: actions/checkout@v2
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
        
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
        
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}   
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
      - name: Download Driver
        run: |
          Invoke-WebRequest -Uri ${{env.KB_DRIVER_RELEASE_ZIP_URL}} -OutFile ${{env.KB_TARGET_ZIP}}
          Expand-Archive -LiteralPath ${{env.KB_TARGET_ZIP}}
          cp ${{env.KB_EXTRACT_DRIVER_PATH}}/Kernel-Bridge.sys ./bin/x64/Release/Kernel-Bridge.sys
          cp ${{env.KB_EXTRACT_DRIVER_PATH}}/Kernel-Bridge.inf ./bin/x64/Release/Kernel-Bridge.inf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: XvddKeyslotUtil
          path: ./bin/x64/Release/
